appointment_with_spec/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles import views
from . import settings
urlpatterns = [
    #re_path(r'^static/(?P<path>.*)$', views.serve),
    path('admin/', admin.site.urls),
    path('app/', include('appointmentapp.urls')),
    path('accounts/', include('allauth.urls'))
]

appointmentapp/urls.py
from django.urls import path
from .views import IndexView, PostListView, PostView, CreatePostView,CreateCommentView


urlpatterns = [
    path('index/',IndexView.as_view(), name='index'),
    path('posts/', PostListView.as_view(), name='posts'),
    path('post/<int:pk>/', PostView.as_view(), name='post_detail'),
    path('post/add/',CreatePostView.as_view(),name='post_add'),
    path('comment/add/',CreateCommentView.as_view(), name='comment_add')
]

appointmentapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# # Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post_text = models.CharField(max_length=500,unique=False)
    post_date = models.DateTimeField(auto_now_add=True,unique=False)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.user.username + ': ' + self.post_text


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=500)
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + ': ' + self.post.post_text + ' : ' + self.comment_text


    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.post.pk})

appointmentapp/forms.py
from django import forms
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Post,Comment

class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ('user',)
        fields = ['post_text']
        labels = {
            "post_text": "Тема для дискуссии"
        }


class CommentForm(ModelForm):
    post_id = forms.CharField(widget = forms.HiddenInput())
    class Meta:
        model = Comment
        exclude = ('user',)
        fields = ['comment_text']
        labels = {
            "comment_text": "Текст комментария"
        }

appointmentapp/views.py
from django.views import View
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.utils import timezone
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, CreateView
from django.contrib.auth.models import User
from .forms import PostForm, CommentForm
from .models import Post
from django.urls import reverse
# Create your views here.


class IndexView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class PostListView(LoginRequiredMixin, ListView, FormView):
    login_url = '/accounts/login/'
    model = Post
    form_class = PostForm
    queryset = Post.objects.order_by('-post_date')
    redirect_field_name = 'redirect_to'
    template_name = 'post_list.html'


class PostView(LoginRequiredMixin, DetailView, FormView):
    model = Post
    template_name = 'post_detail.html'
    form_class = CommentForm


class CreatePostView(LoginRequiredMixin, FormView):
    form_class = PostForm

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = User.objects.get(username=self.request.user)
        post.save()
        return HttpResponseRedirect(post.get_absolute_url())


class CreateCommentView(LoginRequiredMixin, FormView):
    form_class = CommentForm
    def form_valid(self, form):
        comment = form.save(commit=False)
        post_id = form['post_id'].value()
        comment.post = Post.objects.get(id = post_id)
        comment.user = User.objects.get(username=self.request.user)
        comment.save()
        return HttpResponseRedirect(reverse('post_detail', kwargs={'pk': post_id}))

templates/bar.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">{{ user.username }}</a>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'posts' %}">Темы для размышлений
              <!-- <span class="sr-only">(current)</span> -->
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Выйти</a>
          </li>
        </ul>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "bar.html" %}

{% block content %}
{% load static %}
<h1>Reflections</h1>
<p>Привет! {{ user.username }} !!!</p>
{% endblock %}

templates/post_detail.html
{% extends "bar.html" %}

{% block content %}


<div class="">

</div>
<header class="header">Тема для размышлений: {{ post.post_text }}</header>


<div class="comment-part">
  Комментарии:
  <ul>
    {% for comment in post.comment_set.all %}
    <li>{{ comment.comment_text }} {{ comment.comment_date}}</li>
    {% endfor %}
  </ul>
</div>

<form action="/app/comment/add/" method="POST">
  {% csrf_token %}
  <!-- {{ form.as_p }} -->
  {% for field in form %}
  <div class="fieldWrapper">
    {% if field.is_hidden %}
    <input type="hidden" name="{{ field.name}}" value="{{ post.id }}">
    {% else %}
    {{ field.label_tag }} {{ field }}
    {% endif %}
  </div>
  {% endfor %}
  <input type="submit" value="Создать">
</form>

{% endblock %}

templates/post_list.html
{% extends "bar.html" %}
{% load static %}
{% block content %}
<h2>Темы для размышлений</h2>
<table class="table">
  <thead>
    <th scope="col">ИД</th>
    <th scope="col">Создатель</th>
    <th scope="col">Тема</th>
    <th scope="col">Дата создания</th>
  </thead>
  <tbody>
    {% for post in object_list %}
    <tr>
      <th scope="row">{{ post.id }}</th>
      <td>{{ post.user.username }}</td>
      <td><a href="{% url 'post_detail' post.id  %}">{{ post.post_text }}</a></td>
      <td>{{ post.post_date }}</td>
    </tr>
    {% endfor %}

  </tbody>
</table>
<form action="/app/post/add/" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Создать">
</form>
{% endblock %}